### ISSUE TITLE
Odd data being recieved

### ISSUE THREAD

**Issue by moebassist** [eModbus/eModbus#101]
I'm using ModSim as a Modbus RTU server. For some reason, extra bytes are received:

![image](https://user-images.githubusercontent.com/58216179/130032459-0b5e81e0-a1e8-4450-8680-618c865f93df.png)

Black background = received by Modsim
White background = transmitted by Modsim

After a valid Modbus message is received ([000][001][003][000][000][000][051][005][223][000]

there is sometimes junk data that causes timeout:

[064][032[064]064]....etc. 

Any thoughts?

Thanks!

**Comment by Miq1** [comment]
Please see the parallel issue thread, where we currently are trying tosolve a very similar problem. There are 00 bytes observed before and after the message proper, exactly as you do. The original poster had Modsim employed as well, whereas @KevinDesbonnets has a real server connected.

**Comment by moebassist** [comment]
Fixed this issue - wiring was inverted and the serial constructor was called with 'invert=true'. Obviously something weird in the serial port implementation for inversion.

**Comment by Miq1** [comment]
Wonderful! I love issues disappearing! 🤣
