### ISSUE TITLE
100ms lag for every request accept and response

### ISSUE THREAD

**Issue by wildstray** [eModbus/eModbus#105]
#### Do not use to discuss topics! 

**Describe the bug**
I'm using ModbusEthernetServer on ESP32 (240MHz) with W5500. SPI clock 24MHz. I notice really slow performance due to a 100ms (at least) delay repeated for every single accept of TCP request. I looked for delays in the code and I cannot find them (and there is no delay in my code). What is causing these lags?

17:35:57.383 -> [D] 48967| ModbusServer.cpp     [  30] getWorker: Worker found for 03/03
17:35:57.416 -> [D] 48967| ModbusServerTCPtemp.h [ 294] worker: Data response
17:35:57.416 -> [V] Response: @3FFCCE78/29:
17:35:57.416 ->   | 0000: 00 08 00 00 00 17 03 03  14 00 00 00 01 00 02 00  |................|
17:35:57.416 ->   | 0010: 03 00 04 00 05 00 06 00  07 00 08 00 09           |.............   |
17:35:57.483 -> [D] 49086| ModbusServer.cpp     [  30] getWorker: Worker found for 03/03
17:35:57.516 -> [D] 49086| ModbusServerTCPtemp.h [ 294] worker: Data response
17:35:57.516 -> [V] Response: @3FFCCE78/29:
17:35:57.516 ->   | 0000: 00 09 00 00 00 17 03 03  14 00 00 00 01 00 02 00  |................|
17:35:57.516 ->   | 0010: 03 00 04 00 05 00 06 00  07 00 08 00 09           |.............   |
17:35:57.648 -> [D] 49205| ModbusServer.cpp     [  30] getWorker: Worker found for 03/03
17:35:57.648 -> [D] 49205| ModbusServerTCPtemp.h [ 294] worker: Data response
17:35:57.648 -> [V] Response: @3FFCCE78/29:
17:35:57.648 ->   | 0000: 00 0A 00 00 00 17 03 03  14 00 00 00 01 00 02 00  |................|
17:35:57.648 ->   | 0010: 03 00 04 00 05 00 06 00  07 00 08 00 09           |.............   |

**Expected behavior**
Lag free TCP response...

**To Reproduce**

**Example code**
```
#include <ModbusServerEthernet.h>
#define LOCAL_LOG_LEVEL LOG_LEVEL_VERBOSE
#include "Logging.h"

ModbusServerEthernet MBserver;
byte _mac[6] = {0};
IPAddress ip;
IPAddress subnet;
IPAddress gateway;
IPAddress dns;

ModbusMessage FC03(ModbusMessage request) {
  ModbusMessage response;      // The Modbus message we are going to give back
  uint16_t addr = 0;           // Start address
  uint16_t words = 0;          // # of words requested
  request.get(2, addr);        // read address from request
  request.get(4, words);       // read # of words from request
  // Address overflow?
  if ((addr + words) > 20) {
    // Yes - send respective error response
    response.setError(request.getServerID(), request.getFunctionCode(), ILLEGAL_DATA_ADDRESS);
  }
  // Set up response
  response.add(request.getServerID(), request.getFunctionCode(), (uint8_t)(words * 2));
  // Request for FC 0x03?
  if (request.getFunctionCode() == READ_HOLD_REGISTER) {
    // Yes. Complete response
    for (uint8_t i = 0; i < words; ++i) {
      // send increasing data values
      response.add((uint16_t)(addr + i));
    }
  }
  // Send response back
  return response;
}

void setup()
{
    Serial.begin(115200);
    esp_read_mac(_mac, ESP_MAC_ETH);
    Ethernet.begin(_mac, ip, dns, gateway, subnet);
    MBserver.registerWorker(3, READ_HOLD_REGISTER, &FC03);
    MBserver.start(502);
}

```

**Comment by Miq1** [comment]
The time spent is roughly between the "worker found" log line - here the request has been received only a few ms before - and the response hex dump, that is logged immediately before the response is sent. So it really only takes 33ms in between and obviously constantly so, since the second request does as well.
So the time you are missing must have been spent on the TCP communication proper, I am afraid.

**Comment by wildstray** [comment]
...and what about this?
```
 ModbusMessage m = myParent->receive(myClient, 100);
```
I think I found the source of the lags...

**Comment by Miq1** [comment]
@wildstray Can you please download a fresh copy of the library and try again?

Thank you for pointing me to this - it was a silly double loop I had overlooked. Now the TCP receive should terminate at the end of the expected data without further delay.

**Comment by wildstray** [comment]
@Miq1 great, no delays anymore! :+1:

**Comment by Miq1** [comment]
Great! Thanks again for your help.
