### ISSUE TITLE
ANY_SERVER_ID (serverID wildcard)

### ISSUE THREAD

**Issue by wildstray** [eModbus/eModbus#106]
#### Do not use to report bugs!

**Is your feature request related to a problem? Please describe.**
I think it could be a nice idea to have ANY_SERVER_ID or so, like the ANY_FUNCTION_CODE. It would be really useful for Server or Bridge (especially for bridge).

**Describe the solution you'd like**
I tried a "just woking" modification from scratch. Defined a ANY_SERVER_ID as 0xFF (I don't think to find a slave id of 255 never ever) in ModbusTypeDefs.h, than modified ModbusServer.cpp adding this piece of code in ModbusServer::getWorker() between the original code and "// No matching function pointer found
  LOG_D("No matching worker found\n");"
```
  // Search the FC map associated with the ANY_SERVER_ID
  svmap = workerMap.find(ANY_SERVER_ID);
  // Is there one?
  if (svmap != workerMap.end()) {
    // Yes. Now look for the function code in the inner map
    auto fcmap = svmap->second.find(functionCode);;
    // Found it?
    if (fcmap != svmap->second.end()) {
      // Yes. Return the function pointer for it.
      LOG_D("Worker found for ANY/%02X\n", serverID, functionCode);
      return fcmap->second;
      // No, no explicit worker found, but may be there is one for ANY_FUNCTION_CODE?
    } else {
      fcmap = svmap->second.find(ANY_FUNCTION_CODE);;
      // Found it?
      if (fcmap != svmap->second.end()) {
        // Yes. Return the function pointer for it.
        LOG_D("Worker found for ANY/ANY\n", serverID);
        return fcmap->second;
      }
    }
  }
```
Obviosly, it can be written better. Also ModbusBridge<SERVERCLASS>::bridgeWorker() have to be modified (I not yet tried); obviously in this case RTU serverID must be the requested TCP serverID.

**Comment by Miq1** [comment]
The server ID in the Modbus standard is the only item discriminating between multiple servers on a bus. It is the essence of Modbus to explicitly have a client talk to a certain server without others interfering.
There is the "broadcast" server ID 0 (that this library does not support!) In the Modbus standard meant to send request-only messages to all servers on the bus that do not require any responses. 
All else would be problematic, as the RTU bus protocol does not allow for serialization of multiple responses. The TCP Modbus variant technically would be able to work with multiple responses, but the standard does not allow that.

**Comment by Miq1** [comment]
> In industrial devices I often find that slaveID = 0 is used for "me myself" where the device communicate with other TCP slaves (as a master).

That is non-standard then. Anyway, you may do whatever you will find suitable of course.
I implemented the bridge code differently to explicitly not offer some "promiscuous mode", but be able to filter what is bridged and what is not.
