### ISSUE TITLE
Using library to read soil sensor

### ISSUE THREAD

**Issue by Tsaadon** [eModbus/eModbus#137]
Hello,
I am using ESP32 and RS485 Modbus to read a soil sensor, I have used the esp32ModbusRTU library successfully to do it, however, recently I have changed the RS485 communications chip and now it doesn't work anymore, from what I understand the chips are nearly identical, only the new one I'm using is more reliable. The old chip was SP3485EN-L and new one is MAX3485ESA+.
https://www.findic.us/compare/max3485esa-vs-sp3485en-l-40p6xA93G.html

When I tried examining the pulses coming out of the RO pin I noticed the pulses are reversed between the chips.

I tried using the eModbus library and example 4RTU but couldn't get it to work with either chip. 
SP3485EN-L RO pin pulse
![image](https://user-images.githubusercontent.com/66477452/149498534-7538997d-a2bc-4dc8-bb0e-f3d948633a80.png)

MAX3485ESA+ RO pin pulse
![image](https://user-images.githubusercontent.com/66477452/149498571-e7a0fa5b-929e-49a4-9b82-a6b612a512cb.png)

This is the code that works successfully for me with esp32ModbusRTU library using SP3485EN-L:
[SoilSensor.txt](https://github.com/eModbus/eModbus/files/7869634/SoilSensor.txt)

Anyone has any ideas as to why it doesn't work for me and how to adapt the example 4RTU so I can read the relevant parameters, with the eModbus library, in my soil sensor?

Thanks!

**Comment by Miq1** [comment]
Hi,

What is the RO pin you are mentioning? The control pin of the RS485 chip (usually called RE) or the data receive pin (usually RX)?

**Comment by Tsaadon** [comment]
According to the electrical diagram it's RO, but yes it's the data receive pin (RX):
![image](https://user-images.githubusercontent.com/66477452/149507842-46d9778b-c4e6-4d17-b8ac-1cbb36a11cb8.png)
![image](https://user-images.githubusercontent.com/66477452/149508192-0b16f677-00ff-4f34-a180-7af82bc7cad5.png)

**Comment by Miq1** [comment]
I see. If the signal is inverted, you may be lucky exchanging the A and B wires at the chip. If all else fails, the ``Serial.begin()`` call has an optional parameter after the timeout value, that when set to true will invert the Serial signals. But I would bet on the first solution with A/B switched.

**Comment by Tsaadon** [comment]
Unfortunately switching A and B didn't help. 
Can you give me an example of how to use the Serial.begin() command to switch the signals?

**Comment by Miq1** [comment]
Any news on this issue?

**Comment by Tsaadon** [comment]
Yea I tried and unfortunately, it didn't help.

**Comment by Miq1** [comment]
Too bad. I am still almost sure it is an issue with the cabling...

**Comment by Tsaadon** [comment]
Appears you were right, I had 2 resistors missing, when I put them on the signal flipped and now it's reading perfect, thanks!

**Comment by Miq1** [comment]
👍🏻
