### ISSUE TITLE
RTU servers now checking all  messages formally

### ISSUE THREAD

**Issue by Miq1** [eModbus/eModbus#148]
With the recent additions I made for ModbusASCII, I moved the RTU CRC check into ``RTUutils.cpp`` and removed it from ``ModbusServerRTU.cpp`` and ``ModbusClientRTU.cpp``, respectively.

As a side effect now a RTU server will throw a CRC error message whenever a malformed message is seen, even if that is not addressed to that very server.

Is this tolerable or even helpful? 

We _could_ ignore CRC errors on servers like we do for ``TIMEOUT``.

**Comment by Miq1** [comment]
No answer, so we will take the change as set now.

**Comment by drc38** [comment]
Hi, I've been trying to find out the best way to capture the CRC_ERROR message when received by the RTU Server, as it does not appear to propagate to the registerWorker even if the serverId and function codes in the message are correct. Appreciate the help. Thanks

**Comment by Miq1** [comment]
The essence of the CRC is to validate the message as a data block. If a CRC error occurs, you can not tell which part of the message was faulty, it could have been the server ID or function code bytes as any other. You, knowing server IDs in use, are able to guess if both are correct, since you have knowledge about the context that the code does not have. Even if the server ID will match one of the previously seen, there may be an error in it that just happens to result in such.

**Comment by drc38** [comment]
Thanks, yes I understand if a CRC error occurs the rest of the message cannot be relied upon. What I would like to be able to do is propagate the CRC error count to my application. However, I'm unclear how to do so?

**Comment by Miq1** [comment]
If you had an ``onError()`` handler you should be able to count the errors yourself. Using the ``getMessageCount()`` call you can derive a percentage as well.

**Comment by drc38** [comment]
Appreciate the help @Miq1, where in the application would you detect that an error has occurred, at the moment the application is only being called by the registered workers. I see in the RTU client there is a onErrorHandler(MBOnError handler) callback but I couldn't find anything similar on the server side? Would a new task be required monitor for errors?

**Comment by Miq1** [comment]
Ah, I see. Sorry, I was focused on the client side and missed you were referring to the server. I am afraid there is a general ``getErrorCount()`` only at the moment. The individual counts for error codes are not held anywhere right now. It would make sense to at least register the transmission errors on the server side. Let me think about it.
