### ISSUE TITLE
Sending message in RTU mode not working (1.4.0)

### ISSUE THREAD

**Issue by mstegen** [eModbus/eModbus#157]
After upgrading to the latest version, sending a modbus message did not work anymore.

This is causing the issue:

https://github.com/eModbus/eModbus/blob/7a5f8877e5ee426ae8eca634e96ec1dfd5724209/src/RTUutils.cpp#L209

moving it to it's original location (before  rts(LOW);  ) fixed it.

**Comment by mstegen** [comment]
No problem!

**Comment by mstegen** [comment]
Just tested the latest master, and the is fixed.
Thanks.

**Comment by Miq1** [comment]
Thanks a lot! I will publish a hotfix release now.

**Comment by mstegen** [comment]
Yes, was expecting that the library manager(?) would pick up the new version in a hour max, but that does not seem to be the case..

**Comment by Miq1** [comment]
I would need to ``pio publish`` the release to the Platformio library manager, but pio internally is aborting due to some port error. As I wrote, there are dozens of bug reports for that already.

**Comment by mstegen** [comment]
Still no new version available from the Library manager, however the 'changelog' tab in the manager shows the latest release notes.. Weird.

**Comment by Miq1** [comment]
I found a workaround - setting the pio port fixed to 9013 - and was able to publish now. The revised version should be available in a few minutes.

**Comment by mstegen** [comment]
Yes! working now.

**Comment by Miq1** [comment]
:1
