### ISSUE TITLE
Its possible use emodbus on pure uart?

### ISSUE THREAD

**Issue by xury77** [eModbus/eModbus#161]
I would like to use eModbus to connect two devices using a direct UART connection without RS485. Is it possible?

**Comment by Miq1** [comment]
Of course. Just keep in mind to cross the RX and TX lines and give it a go.

This is in fact the way the test sketch uses two UARTs to check the RTU functionality.

**Comment by xury77** [comment]
Please forgive me a newbie question :) This is my first experience with modbus. So when I configure client I don't have to set a RE pin?

**Comment by bertmelis** [comment]
Exactly.

The RE pin is used to control the hardware part of a half-duplex bus. Since you'll only be using the UART you don't need it.

**Comment by xury77** [comment]
Ok. Thanks all for an explanation.
