### ISSUE TITLE
RTUutils.cpp patches

### ISSUE THREAD

**Issue by koen-serneels** [eModbus/eModbus#170]
A project using this library requires some patching to make modbus work correctly.
See https://github.com/SmartEVSE/SmartEVSE-3/issues/2
I'm not sure why this patch is needed and I'm not familiar with modbus.
However, is this patch of such a nature that it could become a permanent fix in this library?
If not, maybe this worth a toggle?

**Comment by Miq1** [comment]
This has been discussed before and is no bug. The symptom that may be cured with the changes is caused by improper biasing of the RS485 bus.
