### ISSUE TITLE
Broadcast Server ID

### ISSUE THREAD

**Issue by OekoSolveMG** [eModbus/eModbus#196]
**Is your feature request related to a problem? Please describe.**
I have a device that first needs to have the server id I want to communicate with set over the broadcast ID. The `ModbusMessage` does not allow creating messages with that ID tough.

**Describe the solution you'd like**
It would probably be the best case to add a solution, where I can send a `ModbusMessage` over the broadcast ID and then perhaps timeout with a seperate error like `BroadCastServerID` to signal that a broadcast ID was used when a timeout occurs.

**Describe alternatives you've considered**
I'm currently simply commenting out the line 441 in `ModbusMessage.cpp`, so I don't check if the server id is invalid anymore or not.

**Additional context**
Additionally line 154 of `ModbusMessage.cpp` sets the server ID as an error 0, that wouldn't work anymore if the check is removed so that would have to be replaced with an ID of 248 or above.

**Comment by Miq1** [comment]
Oh well, the broadcast... It is not explicitly defined by the Modbus standard and the way you describe the application it only would work with a single server of that type on the bus.
We have an internal use for server id 0 already that means 'no valid server'. Changing that would be difficult as it is the intrinsic assumption.
As a workaround, you could try to use an empty ``ModbusMessage`` and fill it with a zero and all following bytes by hand, then send it with ``addRequest``. You will get the timeout error, but at least it could work.

**Comment by Miq1** [comment]
A solution could be to provide a ``broadcast(uint8_t *data, uint8_t len)`` method to the RTU client that will push out the ``data`` buffer prefixed with a zero byte and not wait for a response.

Worth investing time into it?

**Comment by OekoSolveMG** [comment]
**As far as I could see wouldn't it be possible to replace this line:**

_ModbusMessage.cpp / 154_
```cpp
if (MM_data.size() < 2) MM_data[0] = 0; // intentional invalid server ID!
```

**With this:**

_ModbusMessage.cpp / 154_
```cpp
if (MM_data.size() < 2) MM_data[0] = 248; // intentional invalid server ID!
```

**Meaning this code:**

_ModbusMessage.cpp / 440_
```cpp
Error ModbusMessage::checkServerFC(uint8_t serverID, uint8_t functionCode) {
  if (serverID == 0)      return INVALID_SERVER;   // Broadcast - not supported here
  if (serverID > 247)     return INVALID_SERVER;   // Reserved server addresses
  if (FCT::getType(functionCode) == FCILLEGAL)  return ILLEGAL_FUNCTION; // FC 0 does not exist
  return SUCCESS;
}
```
**Could be replaced with this**

_ModbusMessage.cpp / 440_
```cpp
Error ModbusMessage::checkServerFC(uint8_t serverID, uint8_t functionCode) {
  if (serverID > 247)     return INVALID_SERVER;   // Reserved server addresses
  if (FCT::getType(functionCode) == FCILLEGAL)  return ILLEGAL_FUNCTION; // FC 0 does not exist
  return SUCCESS;
}
```

**Comment by OekoSolveMG** [comment]
```broadcast(uint8_t *data, uint8_t len) method to the RTU client```

If that is not possible your idea would work good as well. As long as it is callable from the ModbusClientRTU as well.

**Comment by Miq1** [comment]
> `broadcast(uint8_t *data, uint8_t len) method to the RTU client`
> 
> If that is not possible your idea would work good as well. As long as it is callable from the ModbusClientRTU as well.

Of course, it would **only** be callable from a ``ModbusClientRTU`` instance. It would allow for a guarded treatment of broadcast requests - mind, the normal cycle is to wait for a response after a request, that ultimatively would run into a TIMEOUT with the regular flow.

I will implement the call these days, but am currently blocked by a malfunctioning internet connection. The service guys will come today and hopefully solve the issue.

**Comment by Miq1** [comment]
We got a temporary bypass that is not guaranteed to last, so _carpe diem_ is the motto ?? 

I pushed the changes into the ``Tiny-server`` branch - check that out, please.

### ``ModbusClientRTU`` - send a broadcast request

```
ModbusClientRTU mbcr;
uint8_t message[] = "Broadcast to all folk!";
uint8_t msglen = strlen((const char *)message);
...
Error e = mbcr.addBroadcastMessage(message, msglen);
...
```
Error can be the new ``BROADCAST_ERROR``, meaning the message length was invalid (0 or >253).

There will be no waiting for a response, the request is sent and forgotten.

### ``ModbusServerRTU`` - receiving broadcast requests

```
ModbusServerRTU mbsr;
....
ModbusMessage WorkOnBroadcast(ModbusMessage request) {
  ...
  return NIL_RESPONSE;
}
```
The internal handling does require a ``ModbusMessage`` to be returned, although it is discarded right away. It is advised to return the pre-defined ``NIL_RESPONSE``.

I tested this only sparsely, so any experiences are welcome.

[Update] Line is already down again, I am back to mobile now 😭

**Comment by Miq1** [comment]
Oops, forgot to mention the server's callback register call:
```
registerBroadcastWorker(WorkOnBroadcast);
```

**Comment by OekoSolveMG** [comment]
Thanks a lot will probably have a look tomorrow and good luck with your internet connection.

**Comment by Miq1** [comment]
Will do.
There will be some more modifications, as I am planning to implement the proposed RTU sniffer mode alongside the Broadcast.

**Comment by OekoSolveMG** [comment]
Sure no worries sounds good :D.

**Comment by Miq1** [comment]
Done as intended. Broadcast workers now have a signature of ``void myBCworker(ModbusMessage m)``, so no return value any more.

**Comment by cksoft0807** [comment]
I would like to communicate via ModbusTCP with a device with the unchangeable id 0. 

The workaround does not work for me. When i remove the check i get an error 'Illegal data value'. Is there another possibility?

**Comment by Miq1** [comment]
The server ID of 0 is against all Modbus specifications, a workaround will be highly non-standard of course. I undestand that it may not matter on TCP as much as on RTU to have a valid server ID, but anyway it is not allowed.

Having said that I can only suggest some untested ideas. One would be to not use any of the predefined calls and methods to set up a ``ModbusMessage`` but build them from scratch only. Like
```
ModbusMessage m;
m.add((uint8_t)0), READ_HOLD_REGISTER, (uint16_t)2, (uint16_t)1);
```
This at least will get around the first checks and may even be sent out.
