### ISSUE TITLE
Preprocessor statements excluding non-FreeRTOS devices missing

### ISSUE THREAD

**Issue by Miq1** [eModbus/eModbus#2]
We need to prevent the code being deployed on devices without FreeRTOS (that is, xTask etc.). This should be done by having the preprocessor checking by ``#ifdef`` target system-defined values. 
Supported MCUs: [https://www.freertos.org/RTOS_ports.html](url) 
Interestingly, the ESP32 is missing on that list. Might be one of the "Contributed ports" mentioned.

**Comment by bertmelis** [comment]
This issue will also be used to make the first steps for ESP8266 compatability.

I did a small test and the async version is besides the mutexes good to go. One peculiar thing though. My compiler complains about the implied move constructor for the ModbusMessage. I don't know why this would be different on both platforms.

**Comment by Miq1** [comment]
I think the Arduino core is on a different C++ level as compared to the ESP32 one. That is definitely C++11 plus some - may be the ESP8266 core is behind.

**Comment by Miq1** [comment]
> 
> 
> This issue will also be used to make the first steps for ESP8266 compatability.
> 
> I did a small test and the async version is besides the mutexes good to go. One peculiar thing though. My compiler complains about the implied move constructor for the ModbusMessage. I don't know why this would be different on both platforms.

The problem lies in the ``noexcept = default`` part. looks like the ESP8266 environment does not like that. I removed it and could compile the ModbusMessage stuff without problems.

The LOGDEVICE in ``Logging.h`` is tricky for my application. I have no serial monitor available on the plug and need to redirect that to the Telnet client. I do not have a single, addressable client here, but up to two connections to different hosts, so I need to put out the logging lines twice. May be I will have to add a pseudo print device class again 😁

**Comment by bertmelis** [comment]
Is it OK to wrap all non ESP8266 files in preprocessor guards so they will be excluded from compilation?

Every file that is not compatible with ESP8266 then has `#ifndef ESP8266 /* content */ #endif``` statements.

**Comment by Miq1** [comment]
That will induce device dependence into all source files. If that is unavoidable or all else too complicated, well, okay.

I personally rather am preferring feature-based defines that are set or not in a central header naming the supported devices, like

```
#if defined(ESP32) 
#define USE_MUTEX
... 
#elsif defined(ESP8266) 
... 
#endif
```
You see the pattern?

**Comment by bertmelis** [comment]
That's indeed cleaner. Shall I place all these "features" in a separate `options.h` file?

**Comment by Miq1** [comment]
Yeah, that is exactly what I was thinking of.

**Comment by Miq1** [comment]
I would consider this solved.
