### ISSUE TITLE
Stats: error counter

### ISSUE THREAD

**Issue by zivillian** [eModbus/eModbus#205]
Currently the Bridge and RTU client have counters for
- number of messages
- pending requests
- message count
- active clients
- etc.

It would be great to also have counter for error responses, either in the RTU client or the bridge.

My use case is to show it on my status page:
![grafik](https://user-images.githubusercontent.com/6039253/181387510-0f023f82-ce4d-44ca-8407-6aa757a4c4eb.png)

**Comment by Miq1** [comment]
That would be an easy addition. Thank you for the suggestion, I will implement that eventually.

**Comment by Miq1** [comment]
Rolled out with 1.6

**Comment by bertmelis** [comment]
> @bertmelis I did not add the `errorCount++` to the async code - your domain, I do not want to trample down something unwittingly 😉

I'll implement in a separate PR.
