### ISSUE TITLE
SoftwareSerial support?

### ISSUE THREAD

**Issue by kinsi55** [eModbus/eModbus#218]
**Is your feature request related to a problem? Please describe.**
I am using a ESP-32S and need its hardwareserial for another device (Communicates at 115200 baud) however, need to also talk to a Modbus RTU device at 9600. Unfortunately, this library only supports Hardwareserial.

**Describe the solution you'd like**
Support for SoftwareSerial would be awesome 👍 

**Describe alternatives you've considered**
I suppose my only real alternative is using Serial0 which is kinda icky, trying to put the other device on Software which I dont think is gonna work well, or look for another Library.

**Edit:** I have now stumbled upon [ModbusMaster](https://github.com/4-20ma/ModbusMaster) which does support SoftwareSerial - I will be giving that a test.

**Comment by Miq1** [comment]
There is a [Fork of eModbus](https://github.com/serfreeman1337/eModbus) done by serfreeman1337, that seems to have added SoftwareSerial. I did not try it myself nor have any shares in serfreeman1337's developments, but that could be a solution.

**Comment by kinsi55** [comment]
I ended up using ModbusMaster which works fine for my needs, thanks regardless!

**Comment by Miq1** [comment]
Fine with that. Good luck!
