### ISSUE TITLE
Code has some ignored-qualifiers

### ISSUE THREAD

**Issue by geeks-r-us** [eModbus/eModbus#238]
When I include the library in platformio.ini and have set build flags
`build_flags = -Wall -Wextra -Werror`

I see several errors of type:
>  error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]

I would appreciate if you could clean this. As from my understanding its just to remove the const from the given return values.

**Comment by Miq1** [comment]
Will do in the next days. I noticed that myself but did not rate it a severe issue 😉

**Comment by Miq1** [comment]
Done in ``fix-async``
