### ISSUE TITLE
Add option to use software serial

### ISSUE THREAD

**Issue by I-Connect** [eModbus/eModbus#239]
Hi,

We ran out of HW serials, would it be possible to use/add a constructor for software serial?

We use this library for that:
https://github.com/plerup/espsoftwareserial

Thx

**Comment by Miq1** [comment]
Someone did that in a fork of eModbus already, so yes, that is possible. It is not on our roadmap yet, but I definitely will have a look at it.

**Comment by I-Connect** [comment]
Hey Michael, thx. do you know which fork, there are a lot :-)

Then maybe I will use the fork until it is implemented in the original lib.

**Comment by Miq1** [comment]
Sure, it was [this fork](https://github.com/serfreeman1337/eModbus) by @serfreeman1337.

**Comment by Thermelgy-Repo** [comment]
> Hi,
> 
> We ran out of HW serials, would it be possible to use/add a constructor for software serial?
> 
> We use this library for that: https://github.com/plerup/espsoftwareserial
> 
> Thx

Hai @I-Connect,

I suggest to change the UART HW Serial port to the other IO Pin explicitly, Any pins other than Read only pin & Strapping Pins works. It will closely behave like a HW serial pin.

**Comment by I-Connect** [comment]
the fork you mentioned also had some adaptations for the esp8265, I started with your lib and changed only the software serial part serfreeman did. It seems to work (with SW serial) although it only works on core 1 for me but that could have to do with all the other tasks I am running...

If you want I can create a pull request...?

**Comment by Miq1** [comment]
> If you want I can create a pull request...?

Although this will be welcome, wait a sec, please. @bertmelis currently is trying to refactor the async TCP interface in the ``fix-async`` branch that I would like to merge first and independently. You could of course use that branch to create your PR, since I reckon the affected sources will be disjunct.

**Comment by I-Connect** [comment]
There are indeed only changes in the RTU files so it should not bite but I understand you want to wait, no probs... currently have it implemented in a fork

Let me know when you are ready

**Comment by Miq1** [comment]
👍🏻

**Comment by Miq1** [comment]
Closing this as now it is possible to use any ``Stream``-based interface.

**Comment by I-Connect** [comment]
thx!!
