### ISSUE TITLE
Please add a bool ModbusServerTCPasync::isRunning() function to monitor the async TCP server status

### ISSUE THREAD

**Issue by dsilletti** [eModbus/eModbus#247]
Please add a function to get the status of the async server.
Something simple like this one I implemented would be very useful.

```
bool ModbusServerTCPasync::isRunning() {
  if (server) return true;
  else return false;
}
```

Thank you

**Comment by Miq1** [comment]
@bertmelis is reworking the async code ATM and will consider this.

**Comment by bertmelis** [comment]
@dsilletti I will add something like that.
