### ISSUE TITLE
7Data bit in RTU communication

### ISSUE THREAD

**Issue by MahdiBabaie** [eModbus/eModbus#295]
#### Do not use to report bugs!

**Is your feature request related to a problem? Please describe.**
is it possible to communicate with other plcs or devices using RTU protocol and using & data bit. in your RTU example, only 8 data bit have been used. when i try to communicate with my plc using 7 data bit it get me timeout error. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Code examples welcome!

**Describe alternatives you've considered**

**Additional context**

**Comment by Miq1** [comment]
You need to maintain the 7 bits in your application I am afraid, as Modbus generally is expecting 8 bit bytes. Server adresses may go up to 247, length bytes to 253 and error codes are 128 to 255, so there is no way for 7 bits at all.
