### ISSUE TITLE
TCP03example2 not compiling

### ISSUE THREAD

**Issue by Hancke** [eModbus/eModbus#301]
I am using PlatformIO and get these errors.

[{
	"resource": "/c:/Archive/CODING/PlatformIO/eModbus/.pio/libdeps/esp32dev/ModbusClient/src/ModbusClientRTU.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'class HardwareSerial' has no member named 'setRxFIFOFull'",
	"startLineNumber": 66,
	"startColumn": 10,
	"endLineNumber": 66,
	"endColumn": 10
}]

[{
	"resource": "/c:/Archive/CODING/PlatformIO/eModbus/.pio/libdeps/esp32dev/ModbusClient/src/ModbusServerRTU.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'class HardwareSerial' has no member named 'setRxFIFOFull'",
	"startLineNumber": 76,
	"startColumn": 10,
	"endLineNumber": 76,
	"endColumn": 10
}]

[{
	"resource": "/c:/Archive/CODING/PlatformIO/eModbus/.pio/libdeps/esp32dev/ModbusClient/src/RTUutils.h",
	"owner": "cpp",
	"severity": 8,
	"message": "'class HardwareSerial' has no member named 'setTxBufferSize'",
	"startLineNumber": 58,
	"startColumn": 5,
	"endLineNumber": 58,
	"endColumn": 5
}]

Thx

**Comment by Miq1** [comment]
You need to update your arduino-esp32 core to a version >= 2.0.
