### ISSUE TITLE
Persistent client connection

### ISSUE THREAD

**Issue by FrankBJensen** [eModbus/eModbus#37]
Hi there.

I have been running
https://github.com/andresarmento/modbus-arduino/blob/master/libraries/ModbusIP/ModbusIP.h
with a W5500 cabled connection, connected to a WAGO PLC via TCP, using ESP32. 
I have used the TCP_KEEP_ALIVE option, to make a persistent connection, and it seems to run stable.
Using the TCP_STOP makes the client disconnect, and that results in an modbus error state in the PLC, and it must recover some seconds, before a new connection is possible.

I want to emmigrate this to wireless WiFi.

But no matter what Modbus library I seem to find, there is no option to keep the client connection alive. It always disconnects after sendt packages. I am not sure, if its a core part of WiFi.h, I can not seem to find any workaround for this.

I do not know, what is normal practice, to make a new client for each request, or re-use the same one. I want to update my modbus variables at least every 200mS, and 100mS would we even better.

Is there a workaround for this issue, like the TCP_STOP to TCP_KEEP_ALIVE. Or is it just my PLC that is particular sensitive about this - eg. the ModScan test software so not seem to care, if connection is lost or not.

Hope for some input - or maybe even a fix so that this works for me 👍 :)

Frank

**Comment by bertmelis** [comment]
The clients in this lib don't close the connection by themselves in a typical application. It does close after a certain (configurable) "idle" time. This is for both the sync and async flavour.

Are you sure your server doesn't close the connection?

> The modbus specification says you should not open and close the connection for each request.
