### ISSUE TITLE
at each request, it prints to the monitor of port 1

### ISSUE THREAD

**Issue by yuriy23** [eModbus/eModbus#370]
at each request, it prints to the monitor of port 1. what is this? and how to disable it?
[https://youtu.be/7XZPfmkFHxs?si=e9KptS1P_wW5jK_E](url)

**Comment by Miq1** [comment]
Can you please post the monitor output here? The Youtube- link is not suitable to debug something.

**Comment by yuriy23** [comment]
when the modbus is running, it simply prints 1 to the port monitor.

**Comment by Miq1** [comment]
Without any code, log list or more detailed descriptions I can not make heads or tails from it. The library will not print anything if not told to do so.

**Comment by Miq1** [comment]
@yuriy23 Any progress?

**Comment by yuriy23** [comment]
Good afternoon, I was busy. I was setting up my smd mounting line... I reassembled the project and everything fell into place, no longer prints the number 1. I still don't u
![0-02-05-f00c9a7e9e4e6db5a363fcde285f82d559241a413f5839fc0efcda866465552a_d3b29b2f89c66854](https://github.com/user-attachments/assets/623ef6b4-eda1-4e1b-9eba-86396432ee09)
nderstand the reason. But thanks and the topic can be closed. P.S Sorry for my English

**Comment by Miq1** [comment]
Thanks for the feedback!
