### ISSUE TITLE
Publish eModbus to PlatformIO registry

### ISSUE THREAD

**Issue by Miq1** [eModbus/eModbus#43]
We need to have the eModbus lib listed in PlatformIO - [Registry](https://docs.platformio.org/en/latest/core/userguide/package/cmd_publish.html#cmd-package-publish)

**Comment by bertmelis** [comment]
Do you have a pio account?

As you are this orgs admin, maybe you can do `pio package publish`
https://docs.platformio.org/en/latest/core/userguide/package/cmd_publish.html

**Comment by Miq1** [comment]
Yeah, will try that. Is ``library.json`` complete, up-to-date and formally okay for that? I never dealt with the pio innards before...

**Comment by Miq1** [comment]
Did a publish - we'll see how that processes. I will keep you posted.

**Comment by bertmelis** [comment]
> Yeah, will try that. Is `library.json` complete, up-to-date and formally okay for that? I never dealt with the pio innards before...

Shoot, it's not. There's a mismatch between Github's release version and the version in the library.json/library.properties. But if we update, then we have to change the GH release also.

**Comment by Miq1** [comment]
I changed the internal version in ``library.json`` to ``1.0.0``, so it may come out okay.

**Comment by bertmelis** [comment]
https://platformio.org/lib/show/11682/eModbus
