### ISSUE TITLE
Pointer out of the heap

### ISSUE THREAD

**Issue by francescogirotto** [eModbus/eModbus#44]
Do you know why when I have an error in the translation ID in modbus TCP sometimes a pointer goes out of the heap area and the ESP32 reboot?

![Screenshot 2021-01-04 21-57-03](https://user-images.githubusercontent.com/76907794/103628543-7aff0780-4f3f-11eb-92a8-3926284b133c.png)

**Comment by Miq1** [comment]
Not right away...

Can you put this:
```
monitor_filters = esp32_exception_decoder
```
in your ``platformio.ini`` file and try again? This will give us a readable backtrace to see what originally was causing the exception.

**Comment by Miq1** [comment]
@francescogirotto : Any news?

**Comment by Miq1** [comment]
@francescogirotto : may we assume the bug was caused from another source? Then I would like to close this issue.

**Comment by Miq1** [comment]
Closing this for now.
