### ISSUE TITLE
Modbus RTU slave/server example

### ISSUE THREAD

**Issue by fahadalisarwar1** [eModbus/eModbus#47]
Can you please add an example for Modbus slave in serial mode. I'm new to Modbus and it will help me alot.

**Comment by Miq1** [comment]
I quickly wrote one - please see the examples directory for it.

**Note**: please consider the RTU requirement described [**HERE**](https://emodbus.github.io/requirements#important-note-for-using-the-rtu-bridge-server-and-client)!

**Comment by Miq1** [comment]
Seemingly done.

**Comment by fahadalisarwar1** [comment]
Thank you! cheers
