### ISSUE TITLE
CodeQL is not able to scan

### ISSUE THREAD

**Issue by Miq1** [eModbus/eModbus#50]
The default CodeQL scan script is failing due to being unable to build a target. 

I have no experiences with the Github actions, so could you please have a look, @bertmelis ?

**Comment by Miq1** [comment]
I was wondering if you could do the same here that you did for the build test script? If the Examples will build, almost all of the library will be included. May be that is sufficient for CodeQL?

**Comment by bertmelis** [comment]
Awaiting some progress here, I did run `cppcheck` and no warnings were given except for the magic in the byte order determination functions. `cppcheck` complains about taking the address of a variable at non zero indexes. But there it is on purpose...

**Comment by bertmelis** [comment]
CodeQL is not going to work soon I'm afraid

If we want to have something similar, we might have to look into alternatives:
- cpplint
- cppcheck
- Arduino-lint (something new, didn't look into this yet): https://github.com/arduino/arduino-lint
- https://www.codacy.com/
- https://bettercodehub.com/
- ...

Leaving this road is also an option.

**Comment by Miq1** [comment]
I think we are both using ``cpplint`` and ``cppcheck`` with PlatformIO - aren't we? So I would think it is not worth further effort (yet). My suggestion is to trash the CodeQL script. 

Do you agree?-

**Comment by bertmelis** [comment]
ok, I can integrate cpplint and cppcheck into github actions if needed. I suppose it's not high on the priority list.

**Comment by Miq1** [comment]
👍

**Comment by Miq1** [comment]
Case closed 😁
