### ISSUE TITLE
library doesn't compile in arduino IDE

### ISSUE THREAD

**Issue by TLS1000** [eModbus/eModbus#69]
when attempting to compile the RTU06 example it returns error:

```
In file included from U:\NewPrimary\My Documents\Arduino\libraries\eModbus-master\src\ModbusClientTCPasync.cpp:5:0:

U:\NewPrimary\My Documents\Arduino\libraries\eModbus-master\src\ModbusClientTCPasync.h:9:22: fatal error: AsyncTCP.h: No such file or directory

compilation terminated.
```

**Comment by Miq1** [comment]
You are supposed to have the AsyncTCP library installed - please have a look at the [lib as provided by @me-no-dev](https://github.com/me-no-dev/AsyncTCP)!

**Comment by bertmelis** [comment]
Unfortunately there is no clean way of exclusing source files from compiling so you need to have all the dependencies installed even though they won't be included in the final firmware.

**Comment by TLS1000** [comment]
now it works, thank you

**Comment by Miq1** [comment]
👍
