### ISSUE TITLE
Server Write Example

### ISSUE THREAD

**Issue by bungernut** [eModbus/eModbus#92]
It would be ideal to have an example of a server with writing to a register as well. 
In particular the function for F06 in the example, it is not clear to me how to construct the response message. 

I have a working(ish) example/demo. I'm happy to clean up if this sort of example is useful.
https://gist.github.com/bungernut/fbbf6b352b754029f3d69323d267d19f

Other comments in the example, it is confusing to index modbus registers from 1, modbus allows indexing from 0. I make them array and register indexes match for my sanity.

**Comment by Miq1** [comment]
If you will refer to the Modbus specs, you will find the standard response to a FC 06 request is echoing the request. So in your code you simply will want to do
```
return ECHO_RESPONSE;
```
Regarding your second remark: there is again a section in the Modbus specs suggesting 1 as the very first register address, while adding that the implementation internally may need to use index 0.

You are completely free to accept the 0 address in your code if you like, the check on address being other than 0 has to be ommitted in that case of course.
